### ISSUE TITLE
Page shouldn't be white while scripts are being loaded

### ISSUE THREAD

**Issue by Igoorx** [Igoorx/PyRoyaleClient#15]
While scripts are being loaded the page remains white without any indication that there's something going on. We should show something to the player don't think that the game just stopped working.

**Comment by gyorokpeter** [comment]
I don't seem to figure out how to do it in a way that makes sense.
If I try adding "print statements" (i.e. appendChild to the end with some text) they don't appear until the actual game code starts to run.
Is there a way to simulate the slow loading?

**Comment by Igoorx** [comment]
Look in https://github.com/Igoorx/PyRoyaleClient/blob/master/index.html, there's a style="display: none" in body element.
Also, to simulate slow loading you can use the setTimeout in core.js > loadNext

**Comment by Igoorx** [comment]
@gyorokpeter Can you make a change it to it print correctly what is currently loading? Because as it is now it only show the text about the loading when the loading is already finished...
