### ISSUE TITLE
Convert the question block to a object to allow animation in it

### ISSUE THREAD

**Issue by Igoorx** [Igoorx/PyRoyaleClient#20]

**Comment by Igoorx** [comment]
nvm, i  did a hack to animate the tile: https://github.com/Igoorx/PyRoyaleClient/commit/f862b7ec89f8b93ebff65519b5a37f18ddc37c56

**Comment by gyorokpeter** [comment]
It's spelled "mystery".

**Comment by Igoorx** [comment]
> It's spelled "mystery".
oh sorry lol
