### ISSUE TITLE
I need some directories for the project,

### ISSUE THREAD

**Issue by zgwdg** [Igoorx/PyRoyaleClient#22]
I need some directories for the project, such as: game media img, etc.
Who can provide？

**Comment by randomman21412** [comment]
https://github.com/Igoorx/PyRoyaleClient
download it? 
idk what your asking.
go get a Mario 1 rom if you want that

**Comment by Igoorx** [comment]
This repository is just for the development of the source code. No one will share the game assets here. Go look elsewhere.
