### ISSUE TITLE
unban needed

### ISSUE THREAD

**Issue by randomman21412** [Igoorx/PyRoyaleClient#27]
ok so I got banned for this link: http://info.sonicretro.org/Sonic_Boom_(fan_game)
1 you can only run it on 3.1 2. it says that it was taken down and 3 https://www.youtube.com/watch?v=g6-vyTKYUw0
this guy played the game and did not get a virus and that's the only download I can find so I think it's not a virus also sonic retro is a reputable site also a scan of that page: https://www.virustotal.com/gui/url/ec133b92dde112d071cbdb8da1b97b522e36633b428205f808eb182f5c248fae/detection

**Comment by randomman21412** [comment]
guys i want to be unbanned plz

**Comment by Igoorx** [comment]
This isn't even remotely bound to this repository.
